apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: guestbook-app-of-apps-02
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/nivetha676/argocd.git
    targetRevision: main
    path: app_of_apps_02/workloads/guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true