apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: argocd-single-app

  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://github.com/nivetha676/argocd.git

    targetRevision: HEAD

    path: single_app/app

  destination:

    server: https://kubernetes.default.svc

    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true