apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-single-app
  namespace: demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: nginx-single-app

  template:
    metadata:
      labels:
        app: nginx-single-app

    spec:
      containers:

      - name: nginx
        image: nginx:1.27

        ports:
        - containerPort: 80